### ISSUE TITLE
Breaks OTRS even when disabled on site

### ISSUE THREAD

**Issue by SanderGit** [cowlicks/privacypossum#14]
The Firefox extension breaks OTRS, even when it is disabled on that site. I have to disable the extension to fix the site.
![otrs-errors](https://user-images.githubusercontent.com/5788984/39697605-bec8ce36-51f1-11e8-94f3-b7f1d8f346b8.png)

**Comment by cowlicks** [comment]
Hi @SanderGit was this on https://otrs.com/ ? Do I need to log in to verify it?

I made a release that fixed issues similar to this today. However I can not actually test this case with more info. Did today's release fix this bug?

**Comment by cowlicks** [comment]
From the stack trace, I think the update should fix this. Please feel free to reopen this issue if that isn't the case.

**Comment by SanderGit** [comment]
No the issue still exists.
Now it also blocks a redirect that occurs during login.
This is not otrs.com - it is the installed version of the OTRS software.
